# Generated by Django 4.2.6 on 2023-10-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField()),
                ('delivery_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('HOMEDELIVERY', 'Home Delivery'), ('MEETSOMEWHERE', 'Meed Somewhere')], max_length=20)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
