# Generated by Django 4.2.6 on 2023-10-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themalwas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEWORDER', 'New Order'), ('INPROGRESS', 'In Progress'), ('ADVANCEMADE', 'Advance Made'), ('ORDERREADY', 'Order Ready'), ('PAYMENTINFULL', 'Payment In Full'), ('DELIVERED', 'Delivered')], default='New Order', max_length=50),
        ),
    ]
