# Generated by Django 4.2.6 on 2023-10-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themalwas', '0002_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(choices=[('CAKE', 'Cake'), ('SWEETS', 'Sweets'), ('SNACKS', 'Snacks')], max_length=50),
        ),
    ]
