# Generated by Django 4.2.6 on 2023-10-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themalwas', '0006_alter_order_delivery_type_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New Order', 'New Order'), ('INPROGRESS', 'In Progress'), ('ADVANCEMADE', 'Advance Made'), ('ORDERREADY', 'Order Ready'), ('PAYMENTINFULL', 'Payment In Full'), ('DELIVERED', 'Delivered')], max_length=50),
        ),
    ]
