# Generated by Django 4.2.6 on 2023-10-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themalwas', '0008_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Home Delivery', 'Home Delivery'), ('Meet Somewhere', 'Meet Somewhere')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('New Order', 'New Order'), ('In Progress', 'In Progress'), ('Advance Made', 'Advance Made'), ('Order Ready', 'Order Ready'), ('Payment In Full', 'Payment In Full'), ('Delivered', 'Delivered')], max_length=50),
        ),
    ]
